apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website1
  labels:
    app: static-website1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-website1
  template:
    metadata:
      labels:
        app: static-website1
    spec:
      containers:
      - name: static-website
        image: ajilash25/static-website:6
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
